### ISSUE TITLE
Possible to use inside a lovelace card?

### ISSUE THREAD

**Issue by goodlucknow** [TheLastProject/lovelace-media-art-background#11]
Is it possible to use this inside an entities card for example?
i.e. to set the background of the individual card and not the entire view?

**Comment by TheLastProject** [comment]
Sorry, currently not supported. Could you explain your use case?

**Comment by goodlucknow** [comment]
No worries. Thanks for the response.
I'm just experimenting, I suppose the use case is I'm trying to make my own media player card where mini-media-player can't quite do what I need.
I love the look of this but having it in a container card rather than full screen would be ideal.

**Comment by TheLastProject** [comment]
Hmm, I don't think that would be possible without a big rewrite and that doesn't seem worth it, especially not for the purpose of creating a completely new card.

However, feel free to copy some code if it helps.

Specifically https://github.com/TheLastProject/lovelace-media-art-background/blob/b891e210c03f8e4222b22d460c7bf9795134a3f8/media-art-background.js#L19-L22 would be helpful for retrieving the effect you want. The background image you want to use will just be available as the 'entity_picture' attribute of the Home Assistant entity.

**Comment by goodlucknow** [comment]
Thanks for the tip!
