### ISSUE TITLE
Possible to load own background when paused?

### ISSUE THREAD

**Issue by bwoering** [TheLastProject/lovelace-media-art-background#9]
I previously had my own background loaded in lovelace, this overrides the plugin. But I also don't want the default black background when my players are paused. Would it be possible to make this dynamic?

**Comment by TheLastProject** [comment]
If I understand correctly, if you define a background in lovelace, this plugin stops working and you'll only ever see that background? Could you give me an example configuration of how you set up a background? Because that sounds like a bug.

**Comment by bwoering** [comment]
Sure, 

In my lovelace config your plugin is all the way at the top like this: 

media_art_background:
  blur: 3px
  opacity: 0.2
  transition_opacity: 2s
  entities:
    - media_player.woonkamer_2
    - entity: media_player.woonkamer
      valid_states: 
        - ['playing']
      image_attribute: 'entity_picture'

And when defining my views I have my own background listed as this: 

  - title: Apparaten  
    background: center / cover no-repeat url("/local/background1.jpg") fixed
    icon: mdi:home-outline
    cards:

Let me know if this helps!

**Comment by TheLastProject** [comment]
Fixed in 61a59514ee89cce5b83c347b6d0576603972202d, thanks for reporting!
